---
title: "networks"
author: "Yuxuan Yao"
date: "2020/11/8"
output: 
  html_document:
    theme: cosmo
    highlight: textmate
    css: styles.css
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(igraph)
library(circlize)
library(knitr)
opts_chunk$set(fig.show = "hold")
```

```{r message=FALSE}
# select rows
data=readxl::read_xls('data/State_to_State_Migrations_Table_2018.xls', skip=4)
```

### Extract the data in the form of a data frame with 3 columns: source, target and count; the last column will contain the numbers of people who migrated from the source state to the target state in 2018
```{r message=FALSE, warning=FALSE}
# Set the target column
data = dplyr::rename(data, 'target'='Current residence in...1')
# remove no need columns
data = select(data,-contains('Current residence in') )
data = select(data,-seq(3,119,2) )
data = select(data,-c(2:5))
# view data
data
# the amount of columns is 56
# ready for the rename processing
col_names = colnames(data[,2:56])
new_col_names = as.character(unlist(data[1, 2:56], use.names = FALSE))
# rename
data = rename_at(data,vars(col_names),~ new_col_names)
# drop NULL values and no need columns
data = drop_na(data)
data = filter(data,!target %in% c('United States2','Puerto Rico','Guam') )
data = gather(data,key='source', value='count' ,-target)
data$count = data$count %>% as.numeric()
data = data[,c(2,1,3)]
``` 


### view data
```{r}
# finished and view data
head(data)
```



### Networks (Select New York, Texas, District of Columbia and Maryland)
```{r}
temp = filter(data,source %in% c('New York', 'Texas', 'District of Columbia', 'Maryland'))
tmep = group_by(temp,source)
temp = top_n(temp, 10, wt=count)
network1 = graph.data.frame(temp)
network2 = temp
plot(network1,layout=layout_in_circle(network1))
title('Top 10 People Moving States of \n New York, Texas, District of Columbia and Maryland')
chordDiagram(network2, annotationTrack = c('grid'),preAllocateTracks = list(track.height = max(strwidth(unlist(dimnames(network2))))))
circos.track(track.index = 1, panel.fun = function(x, y) {circos.text(CELL_META$xcenter, CELL_META$ylim[1], CELL_META$sector.index, facing = "clockwise")},bg.border = NA) 
title("Top 10 People Moving States of \n New York, Texas, District of Columbia and Maryland")
```
